# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-20 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleicao', '0002_auto_20171120_2013'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eleitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128)),
            ],
        ),
        migrations.DeleteModel(
            name='VotoBranco',
        ),
        migrations.AddField(
            model_name='voto',
            name='branco',
            field=models.NullBooleanField(),
        ),
    ]
